[package]
name = "bad_ring_buffer"
version = "0.1.0"
authors = ["Thomas Andolf <thomas.andolf@truesec.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
